function(SharedList args)
  list(GET ARGV 0 RetVal)
  list(REMOVE_AT ARGV 0)
  set(Ret)
  foreach (V ${ARGV})
    set (SAVE_CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
    get_filename_component(out_name ${V} NAME_WE)
    set (CMAKE_FIND_LIBRARY_SUFFIXES .dll .so)
    string(REGEX REPLACE "^lib" "" out_name ${out_name})
    set(out_file "NOTFOUND")
    find_library(out_file ${out_name} NOCACHE)
    if(out_file)
      list(APPEND Ret ${out_file})
    else()
      message(FATAL_ERROR "Library ${out_name} not found !!!!" )
    endif()
    set (CMAKE_FIND_LIBRARY_SUFFIXES ${SAVE_CMAKE_FIND_LIBRARY_SUFFIXES})
  endforeach()
  set(${RetVal} ${Ret} PARENT_SCOPE)
endfunction()
